export const SET_PRODUCTS = "SET_PRODUCTS"
export const SET_PRODUCT = "SET_PRODUCT"
export const SET_FEATURED_PRODUCT = "SET_FEATURED_PRODUCT"
export const SET_RELATED_PRODUCTS = "SET_RELATED_PRODUCTS"